### ISSUE TITLE
Can't edit template name

### ISSUE THREAD

**Issue by seba-wetzel** [sdinesh86/template-generator#12] opened 2017-01-16 19:45 UTC
I'm using last version of the plugin, atom version 1.13.0 x64 under ubuntu 16.04 x64.
I can create a new template, but I can't rename it. I have to edit manually the templates.cson if I wanna edit the template names

**Comment by sdinesh86** [comment] 2017-01-19 11:55
duplicate of #5

**Closed by sdinesh86** 2017-01-19 11:55 UTC
