### ISSUE TITLE
Editing file/directory/group name doesn't work on windows

### ISSUE THREAD

**Issue by ifrim** [sdinesh86/template-generator#5] opened 2016-05-11 07:24 UTC
I have atom 1.7.3 on windows 7 and when I double click on a file/directory/group name it doesn't turn into an editable input.

**Comment by sdinesh86** [comment] 2016-05-11 10:58
I don't have a windows 7 machine at home, so will check this at work tomorrow

**Comment by sdinesh86** [comment] 2016-05-16 10:49
@ifrim I am not able to reproduce the issue on my side.

Can you please give me more details

**Comment by ifrim** [comment] 2016-05-16 12:01
Hmm, maybe there are conflicts with other plugins I have installed. 
I'll do some more tests and get back with a comment.
Thanks for your time.

**Comment by sdinesh86** [comment] 2016-05-24 04:09
@ifrim any update on this or is it ok to close this issue ?

**Comment by ifrim** [comment] 2016-05-24 05:42
I think it is ok to close. I didn't find a cause yet, didn't had too much time really. If I'll have meaningful information I'll leave a comment. Thanks.

**Comment by Poncho0794** [comment] 2017-01-16 02:04
I'm working on a mac and I got the same issue, the version of the package I have is 0.14.0
![image](https://cloud.githubusercontent.com/assets/6852617/21968765/d6df4b5a-db5d-11e6-9693-57b8821155d0.png)

**Comment by sdinesh86** [comment] 2017-01-19 11:55
I am working on it and will get back asap

**Comment by hartreed** [comment] 2017-01-27 19:16
I'm also experiencing this issue on Mac with version 0.14.0 and Atom 1.13. It was working previously, and seems to have broken when I updated other deprecated packages, wiping out all of my created templates as well. 

Thanks a ton for creating this package, I've found it to be incredibly helpful and quick to use once you figure out the quirks.

**Comment by mindfullsilence** [comment] 2017-02-09 04:43
If it helps I have the same issue. Still have the templates I had already created prior to update with variable names working fine. New items can't be renamed. 

Mac Sierra, 
package 0.14.0, 
atom 1.13.1 x64

I took a look through your coffee and didn't see anything crazy. all seemed really straight forward actually, so I jumped into the changelogs for the recent atom 1.13 update. I have no idea if this relates at all, but it was the only _potential_ change that I could see causing issues. Hopefully not sending you down a rabbit hole but thought it might help:

https://github.com/atom/atom/pull/13687

**Comment by mindfullsilence** [comment] 2017-02-09 04:50
For those who want a temporary fix, you can change where your template files are stored in the settings of the package. There is a field called "Templates File". Set that to something accessible with a cson extension. Then create your templates as necessary (you still won't be able to change their name, but make them anyway). Then when you're done, edit the cson file the package generated. It's pretty straight forward to read, so you should be able to figure it out from there.

**Comment by sdinesh86** [comment] 2017-02-10 15:17
Sorry guys couldnt work on this, since was out on vacations, I will look into this ASAP.

**Closed** 2017-02-19 11:43 UTC
Labels: bug
