### ISSUE TITLE
Uncaught TypeError: Cannot read property 'mainModule' of undefined

### ISSUE THREAD

**Issue by paulomogollon** [sdinesh86/template-generator#14] opened 2017-06-18 15:13 UTC
[Enter steps to reproduce:]
When unsing Nuclide package
1. Open the Template Selector Panel (Alt+n)
2. Select a Template

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.12.5
**Thrown From**: [template-generator](https://github.com/sdinesh86/template-generator) package 0.15.0

### Stack Trace

Uncaught TypeError: Cannot read property 'mainModule' of undefined

```
At /Users/wanchope/.atom/packages/template-generator/lib/template-generator-template-selector-dialog.coffee:50

TypeError: Cannot read property 'mainModule' of undefined
  at TemplateSelectorListView.module.exports.TemplateSelectorListView.confirmed (/packages/template-generator/lib/template-generator-template-selector-dialog.coffee:50:5)
  at TemplateSelectorListView.module.exports.SelectListView.confirmSelection (/packages/tab-control/node_modules/atom-space-pen-views/lib/select-list-view.js:338:21)
  at /packages/tab-control/node_modules/atom-space-pen-views/lib/select-list-view.js:139:19)
  at HTMLOListElement.dispatch (/packages/tab-control/node_modules/jquery/dist/jquery.js:4435:9)
  at HTMLOListElement.elemData.handle (/packages/tab-control/node_modules/jquery/dist/jquery.js:4121:28)

```

### Commands

```
     -1:32.3.0 core:select-down (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
  5x -1:09.0 nuclide-related-files:jump-to-next-related-file (div.nuclide-file-tree.focusable-panel.tree-view)
     -0:41.6.0 application:open-your-keymap (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
     -0:35.8.0 core:cut (input.hidden-input)
     -0:35.1.0 editor:newline (input.hidden-input)
     -0:34.7.0 core:paste (input.hidden-input)
     -0:33.5.0 core:move-up (input.hidden-input)
     -0:32.1.0 core:copy (input.hidden-input)
     -0:31.6.0 core:paste (input.hidden-input)
     -0:30.7.0 core:backspace (input.hidden-input)
     -0:30.2.0 core:move-up (input.hidden-input)
     -0:28.8.0 editor:newline (input.hidden-input)
     -0:20.8.0 autocomplete-plus:confirm (input.hidden-input)
     -0:19.3.0 core:save (input.hidden-input)
     -0:14.8.0 template-generator:toggle-template-generator (div.nuclide-file-tree.focusable-panel.tree-view)
     -0:13.9.0 nuclide-datatip:toggle (input.hidden-input)
```

### Non-Core Packages

```
atom-react-native-autocomplete 0.0.27 
autocomplete-js-import 1.4.0 
busy-signal 1.4.3 
chrome-color-picker 0.8.0 
emmet 2.4.3 
haskell-grammar 0.4.0 
highlight-selected 0.13.1 
intentions 1.1.2 
language-babel 2.66.0 
language-graphql 0.9.0 
language-ini 1.19.0 
language-javascript-jsx 0.3.7 
language-lua 0.9.11 
language-ocaml 1.9.5 
language-rust 0.4.10 
language-swift 0.5.0 
language-thrift 1.0.2 
linter 2.2.0 
linter-eslint 8.2.1 
linter-ui-default 1.6.1 
MagicPython 1.0.10 
merge-conflicts 1.4.5 
nuclide 0.232.0 
nuclide-format-js 0.0.36 
pigments 0.39.1 
react 0.16.2 
set-syntax 0.3.2 
sort-lines 0.14.0 
tab-control 0.6.10 
template-generator 0.15.0 
tool-bar 1.1.0 
```

**Comment by darioespinoza** [comment] 2017-11-23 12:15
has solucionado el problema tengo el mismo error

**Comment by sdinesh86** [comment] 2017-12-18 04:55
I am not able to reproduce this issue so closing it.

**Closed by sdinesh86** 2017-12-18 04:55 UTC
